# Generated by Django 5.0.3 on 2024-03-28 00:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cursos', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del curso')),
                ('detalles', ckeditor.fields.RichTextField(verbose_name='Detalles del curso')),
                ('campos_disponibles', models.IntegerField(default=0, verbose_name='Campos Disponibles')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('oferta', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Oferta/Descuento')),
                ('fecha_caducidad', models.DateTimeField(verbose_name='Fecha de caducidad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['campos_disponibles'],
            },
        ),
    ]
